// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RR.DataBaseConnect;

#nullable disable

namespace RR.DataBaseConnect.Migrations
{
    [DbContext(typeof(DataBaseAccess))]
    partial class DataBaseAccessModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RR.Models.EmployeeInfo.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserPassId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("UserPassId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("RR.Models.EmployeeInfo.EmployeeRoles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmpId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdOfRole")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("EmployeeRoles");
                });

            modelBuilder.Entity("RR.Models.EmployeeInfo.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RR.Models.EmployeeInfo.UserNamePassword", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserNamePassword");
                });

            modelBuilder.Entity("RR.Models.PeerToPeerInfo.PeerToPeer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AwardCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("int");

                    b.Property<int?>("CampaignsId")
                        .HasColumnType("int");

                    b.Property<string>("Citation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<string>("NominatorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PeerToPeerResultsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignsId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("PeerToPeerResultsId");

                    b.ToTable("PeerToPeer");
                });

            modelBuilder.Entity("RR.Models.PeerToPeerInfo.PeerToPeerResults", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Citation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("NominatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomineeId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("PeerToPeerResults");
                });

            modelBuilder.Entity("RR.Models.Rewards_Campaigns.Campaigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CampaignName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.Property<int?>("RewardTypesId")
                        .HasColumnType("int");

                    b.Property<string>("StartDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RewardTypesId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("RR.Models.Rewards_Campaigns.RewardType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RewardTypes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RewardType");
                });

            modelBuilder.Entity("RR.Models.EmployeeInfo.Employee", b =>
                {
                    b.HasOne("RR.Models.EmployeeInfo.UserNamePassword", "UserNamePassword")
                        .WithMany()
                        .HasForeignKey("UserPassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserNamePassword");
                });

            modelBuilder.Entity("RR.Models.EmployeeInfo.EmployeeRoles", b =>
                {
                    b.HasOne("RR.Models.EmployeeInfo.Roles", "role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("RR.Models.PeerToPeerInfo.PeerToPeer", b =>
                {
                    b.HasOne("RR.Models.Rewards_Campaigns.Campaigns", "Campaigns")
                        .WithMany()
                        .HasForeignKey("CampaignsId");

                    b.HasOne("RR.Models.EmployeeInfo.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.HasOne("RR.Models.PeerToPeerInfo.PeerToPeerResults", "PeerToPeerResults")
                        .WithMany()
                        .HasForeignKey("PeerToPeerResultsId");

                    b.Navigation("Campaigns");

                    b.Navigation("Employee");

                    b.Navigation("PeerToPeerResults");
                });

            modelBuilder.Entity("RR.Models.PeerToPeerInfo.PeerToPeerResults", b =>
                {
                    b.HasOne("RR.Models.EmployeeInfo.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("RR.Models.Rewards_Campaigns.Campaigns", b =>
                {
                    b.HasOne("RR.Models.Rewards_Campaigns.RewardType", "RewardTypes")
                        .WithMany()
                        .HasForeignKey("RewardTypesId");

                    b.Navigation("RewardTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
